---
# tasks file for db
- name: install mariadb-server
  yum: name={{ item }} state=present
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python
    - mysql-connector-python
 
- name: start mysqld
  systemd:
    name: mariadb
    state: started
    enabled: true
 
- name: open port 3306
  firewalld:
    port: 3306/tcp
    permanent: true
    state: enabled
    immediate: yes
  notify: restart firewalld
 
- name: check if root password for mariadb is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check
 
- name: set mariadb root password for first time
  mysql_user:
    name: root
    password: "1234"
    host_all: yes
    state: present
  when: root_pwd_check.rc == 0

- name: flush privileges
  command: 'mysql -ne "{{ item }}" -uroot -p"1234"'
  with_items:
   - FLUSH PRIVILEGES
  changed_when: False
